# Credits By github.com/UserOfGTG

name: WinCRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AWtgzh5Laswr2CwtL8rRu3aQkSLV5QGAwnQqOhAnb97tdAuWAElOqI3kxhZp47szOrgLOQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
        required: true
      pincode:
        description: '000000'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Preparing to Setup.. 
      run: ./start.ps1
    - name: Starting CRD... 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Done! Keep Active. 
      run: ./timeout.ps1
